packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  es5-ext: false
  esbuild: false
  simple-git-hooks: false
  vue-demi: false
shamefullyHoist: true
ignoreWorkspaceRootCheck: true
linkWorkspacePackages: true
